package model;

import javax.persistence.*;

/**
 * User Entity for SQL table 'ADMINISTRATEUR'
 */
@Entity
@Table(name = "ADMINISTRATEURoooooo")
public class Admin extends Person {

    /**
     * 'username' -> 'IDENTIFIANT'
     * Max length of 50 'car' (default) && not NULL
     */
    @Column(name = "IDENTIFIANT", length = 50, nullable = false)
    private String username;

    public Admin() {
        // TODO AUTOGENERATED
    }

    public long getIdAdministrateur() {
        return Person.getIdUtilisateur();
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}
