package model;

import javax.persistence.*;

/**
 * User Entity for SQL table 'PERSONNE'
 */
@Entity
@Inheritance(strategy=InheritanceType.JOINED)
public class Person {

    /**
     * id : "idUtilisateur"
     * type : long
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_utilisateur", nullable = false)  // AutoIncremental
    private static long idUtilisateur;

    /**
     * 'lastName' -> 'NOM'
     * Max length of 255 'car' (default) && not NULL
     */
    @Column(name = "NOM", length = 255, nullable = false)
    private String lastName;

    /**
     * 'firstName' -> 'PRENOM'
     * Max length of 50 'car' && not NULL
     */
    @Column(name = "PRENOM", length = 50, nullable = false)
    private String firstName;

    /**
     * 'userEmail' -> 'EMAIL'
     * Max length of 50 'car' && not NULL
     */
    @Column(name = "EMAIL", length = 50, nullable = false)
    private String userEmail;

    /**
     * 'userPwd' -> 'MOT_DE_PASSE'
     * Max length of 255 'car' (default) && not NULL
     */
    @Column(name = "MOT_DE_PASSE", length = 50, nullable = false)
    private String userPwd;

    public Person() {
        // TODO AUTOGENERATED
    }

    public static long getIdUtilisateur() {
        return idUtilisateur;
    }

    public static void setIdUtilisateur(long idUtilisateur) {
        Person.idUtilisateur = idUtilisateur;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getUserPwd() {
        return userPwd;
    }

    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }
}
