package model;

import javax.persistence.*;
import java.util.Date;

/**
 * User Entity for SQL table 'UTILISATEUR'
 */
@Entity
@Table (name = "UTILISATEUR")
public class User extends Person{

    /**
     * 'numberOfSparks' -> 'NOMBRE_SPARK'
     * Double && not NULL (at least equal to zero)
     */
    @Column(name = "NOMBRE_SPARK", nullable = false)
    private Double numberOfSparks;

    /**
     * 'registrationDate' -> 'DATE_INSCRIPTION'
     * Datetime && not NULL
     */
    @Column(name = "DATE_INSCRIPTION", nullable = false)
    private Date registrationDate;

    /**
     * 'isPMR' -> 'isPMR'
     * Boolean && not NULL
     */
    @Column(name = "isPMR", nullable = false)
    private Boolean isPMR;

    /**
     * Default constructor
     */
    public User() {
        // TODO AUTOGENERATED
    }

    public long getId_utilisateur() {
        return Person.getIdUtilisateur();
    }

    public void setId_utilisateur(long id_utilisateur) {
        Person.setIdUtilisateur(id_utilisateur);
    }

    public Double getNumberOfSparks() {
        return numberOfSparks;
    }

    public void setNumberOfSparks(Double numberOfSparks) {
        this.numberOfSparks = numberOfSparks;
    }

    public Date getRegistrationDate() {
        return registrationDate;
    }

    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    public Boolean getPMR() {
        return isPMR;
    }

    public void setPMR(Boolean PMR) {
        isPMR = PMR;
    }
}
