package model;

import javax.persistence.*;
import java.util.Date;

/**
 * User Entity for SQL table 'UTILISATEUR'
 */
@Entity
@Table (name = "UTILISATEUR")
public class User {

    /**
     * id : "id_utilisateur"
     * type : long
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(nullable = false)  // AutoIncremental
    private long id_utilisateur;

    /**
     * 'lastName' -> 'NOM'
     * Max length of 255 'car' (default) && not NULL
     */
    @Column(name = "NOM", length = 255, nullable = false)
    private String lastName;

    /**
     * 'firstName' -> 'PRENOM'
     * Max length of 50 'car' && not NULL
     */
    @Column(name = "PRENOM", length = 50, nullable = false)
    private String firstName;

    /**
     * 'userEmail' -> 'EMAIL'
     * Max length of 50 'car' && not NULL
     */
    @Column(name = "EMAIL", length = 50, nullable = false)
    private String userEmail;

    /**
     * 'userPwd' -> 'MOT_DE_PASSE'
     * Max length of 255 'car' (default) && not NULL
     */
    @Column(name = "MOT_DE_PASSE", length = 50, nullable = false)
    private String userPwd;

    /**
     * 'numberOfSparks' -> 'NOMBRE_SPARK'
     * Double && not NULL (at least equal to zero)
     */
    @Column(name = "NOMBRE_SPARK", nullable = false)
    private Double numberOfSparks;

    /**
     * 'registrationDate' -> 'DATE_INSCRIPTION'
     * Datetime && not NULL
     */
    @Column(name = "DATE_INSCRIPTION", nullable = false)
    private Date registrationDate;

    /**
     * 'isPMR' -> 'isPMR'
     * Boolean && not NULL
     */
    @Column(name = "isPMR", nullable = false)
    private Boolean isPMR;

    /**
     * Default constructor
     */
    public User() {
        // TODO AUTOGENERATED
    }

    public long getId_utilisateur() {
        return id_utilisateur;
    }

    public void setId_utilisateur(long id_utilisateur) {
        this.id_utilisateur = id_utilisateur;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getUserPwd() {
        return userPwd;
    }

    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    public Double getNumberOfSparks() {
        return numberOfSparks;
    }

    public void setNumberOfSparks(Double numberOfSparks) {
        this.numberOfSparks = numberOfSparks;
    }

    public Date getRegistrationDate() {
        return registrationDate;
    }

    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    public Boolean getPMR() {
        return isPMR;
    }

    public void setPMR(Boolean PMR) {
        isPMR = PMR;
    }
}
